name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main when .bumpversion.cfg version is updated
  push:
    branches:
      - main
    paths:
      - .bumpversion.cfg

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          fetch-depth: 0
      - run: git fetch --tags --force origin # WA: https://github.com/actions/checkout/issues/882

      - name: Test release condition
        id: release
        run: |
          set -eu -o pipefail
          RELEASE=false
          PRIOR_VERSION=$(git describe --abbrev=0 --tags || true)
          RELEASE_VERSION=$(grep current_version .bumpversion.cfg | sed 's/^.*= //' )
          if [[ "$PRIOR_VERSION" != "$RELEASE_VERSION" ]]; then RELEASE=true; fi
          echo "condition=${RELEASE}"
          echo "version=${RELEASE_VERSION}"
          echo "condition=${RELEASE}" >> "$GITHUB_OUTPUT"
          echo "version=${RELEASE_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Create release
        if: steps.release.outputs.condition == 'true'
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          name: ${{ steps.release.outputs.version }}
          tag_name:  ${{ steps.release.outputs.version }}
          generate_release_notes: true
          target_commitish: ${{ env.GITHUB_REF }}
          token: ${{ secrets.GH_RELEASES_TOKEN }}
