name: Run test jobs
on:
  workflow_call:
    inputs:
      mockstacktest-enable:
        description: Controls whether to run the mockstacktest job
        default: true
        required: false
        type: boolean

jobs:
  mockstacktest:
    if: inputs.mockstacktest-enable
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Install docker-compose
        run: make docker-compose/install

      - name: Start the mock AWS stack
        run: make mockstack/up

      - name: Apply Terraform test configs in mock AWS stack
        run: make mockstack/pytest

      - name: Cleanup the mock AWS stack
        run: make mockstack/clean
